### ISSUE TITLE
Collections default ttl is broken (sorted sets)

### ISSUE THREAD

**Issue by bruuuuuuuce** [momentohq/client-sdk-go#116]
When incrementing an element in a sorted set, if you don't pass in a ttl, we should be using the default ttl. For unary operations, we check to make sure that the request ttl isnt 0, and if it isnt we use it, else we use the default client configured ttl

```
func (c *DefaultScsClient) Set(ctx context.Context, request *CacheSetRequest) error {
	if err := isCacheNameValid(request.CacheName); err != nil {
		return err
	}
	ttlToUse := c.defaultTTL
	if request.TTL != time.Duration(0) {
		ttlToUse = request.TTL
	}
```

We need to perform a similar check for sorted sets ttls. These ttls are a bit different since they are more than just a duration, they also have a boolean flag to determine if we should refresh the ttl of the item or not `CollectionTTL: utils.CollectionTTL{RefreshTtl: true, Ttl: 60 * time.Second},`.

This code below should be respecting the default 60 second ttl that was set for the cache client, however items are getting evicted immediately.
```
client, err := incubating.NewScsClient(&momento.SimpleCacheClientProps{
	Configuration:      config.LatestLaptopConfig(),
	CredentialProvider: credProvider,
	DefaultTTL:         60 * time.Second,
})
if err != nil {
	panic(err)
}
	
response, err := client.SortedSetIncrement(ctx, &incubating.SortedSetIncrementRequest{
		CacheName:   cacheName,
		SetName:     "game1",
		ElementName: momento.StringBytes{Text: "Allen"},
		Amount:      2,
	})

	if err != nil {
		panic(err)
	} else {
		switch r := response.(type) {
		case *incubating.SortedSetIncrementResponseSuccess:
			fmt.Println(fmt.Sprintf("new value %f", r.Value))
		}
	}
```

As a part of this ticket, we should also audit other collections apis to make sure they also respect the default ttl

**Comment by schwern** [comment]
Try it with the latest main, please.
