### ISSUE TITLE
Align default arguments for sorted set fetch

### ISSUE THREAD

**Issue by bruuuuuuuce** [momentohq/client-sdk-go#124]
According to our api docs, `order` and `limit` should both be required arguments as part of the fetch request https://www.notion.so/momentohq/SDK-API-Methods-Spec-cf12e4db2535405ca2acc3608814b083#7e9ed5fca577491fb73e38161752e92b. However, the following go code compiles
```
client.SortedSetFetch(ctx, &momento.SortedSetFetchRequest{
        cacheName: "test",
        setName: "set",
})

client.SortedSetFetch(ctx, &momento.SortedSetFetchRequest{})
```

Its not clear what the default ordering is or what the default limit is in this code. We should change our function signatures to ensure that all required variables are set, else have it be a compile time failure.

**Comment by schwern** [comment]
I'm fine with having the default limit be "All" and not making the user pass that in.

The current default is Ascending because Protocol Buffers will default to 0. I'm also happy with that as the default, its the normal default for sort functions.

**Comment by schwern** [comment]
As for `client.SortedSetFetch(ctx, &momento.SortedSetFetchRequest{})` compiling, that'show Go works. You don't need to specify every field of a struct.

We discussed changing from passing in a struct to specifying all the fields as method arguments, but Go lacks optional parameters so it would force users to pass in everything to every method.
