### ISSUE TITLE
Make CollectionTTL a pointer and try to make behave like our other SDKS when no value passed

### ISSUE THREAD

**Issue by eaddingtonwhite** [momentohq/client-sdk-go#174]

**Comment by poppoerika** [comment]
Default `TTL` behavior when no value is passed:
- use default ttl that is specified when a cache client is created
- refresh ttl is true by default
.NET SDK default TTL treatment: https://github.com/momentohq/client-sdk-dotnet/blob/4122f30029c03f2db173656a1e627fd39fdd0bca/src/Momento.Sdk/Requests/CollectionTtl.cs#L26
