### ISSUE TITLE
Spike on byte keys for maps do we need to change up how we do `momento.Bytes()`

### ISSUE THREAD

**Issue by eaddingtonwhite** [momentohq/client-sdk-go#180]
Currently our dictionaries can only support `map[string]momento.Value` we should spike to see what we can do if there is way to make more flexible so can support byte keys in the map in clean way for users.

Do we need to make any changes to `momento.Bytes()` prior to 1.0 release?

**Comment by pgautier404** [comment]
Addressed in ba3fe975 with the inclusion of an `Element` type that contains `ElemField` and `ElemValue`, both with the `Value` type. Also included are convenience methods to convert from maps with string, []byte, or Value values to `[]Element`.
