### ISSUE TITLE
Make SDK tests simpler to new devs

### ISSUE THREAD

**Issue by eaddingtonwhite** [momentohq/client-sdk-go#187]
- [x] `TEST_AUTH_TOKEN` not being set resulted in nil pointer error
- [x] `TEST_CACHE_NAME` not being set worked fine but confused new dev coming on to repo if needed

**Comment by schwern** [comment]
We can't use a single cache name for testing, it will conflict when tests are run simultaneously on Github or if we want to test in parallel, so TEST_CACHE_NAME is gone.

I'll remove it from the CONTRIBUTING doc.

**Comment by pgautier404** [comment]
Tests were swallowing the credential provider error message informing the user that their environment variable was not set or was empty. This was fixed in 17f677ee.
