### ISSUE TITLE
protoc is failing due to inability to find extensions.proto

### ISSUE THREAD

**Issue by pgautier404** [momentohq/client-sdk-go#312]
`cachepubsub.proto` is importing `extensions.proto`, but for some reason `protoc` is unable to find that file, despite the fact that it's in the same directory as the others. Here's the relevant output from running `make protos` in the golang SDK root:

```
protoc -I=internal --go_out=internal --go_opt=paths=source_relative --go-grpc_out=internal --go-grpc_opt=paths=source_relative internal/protos/*.proto
extensions.proto: File not found.
protos/cachepubsub.proto:3:1: Import "extensions.proto" was not found or had errors.
```

I had a similar issue trying to run protoc in the web SDK, and in that case I was able to resolve the error by adding `extensions.proto` as the first proto file in an explicit list of files to compile. However, that approach doesn't work with golang, and the error is returned regardless of whether or not I compile `extensions.proto` before `cachepubsub.proto`.

**Comment by kvcache** [comment]
So, first place to look:
```
$ protoc --help
Usage: protoc [OPTION] PROTO_FILES
Parse PROTO_FILES and generate output based on the options given:
  -IPATH, --proto_path=PATH   Specify the directory in which to search for
                              imports.  May be specified multiple times;
                              directories will be searched in order.  If not
                              given, the current working directory is used.
                              If not found in any of the these directories,
                              the --descriptor_set_in descriptors will be
                              checked for required proto file.
```

Then, to understand how that works you can refer to the relevant part of the spec for the feature that isn't working as you expect:
https://protobuf.dev/programming-guides/proto3/#importing
> The protocol compiler searches for imported files in a set of directories specified on the protocol compiler command line using the -I/--proto_path flag. 

Looking at your proto, you can see that it is referring to a path directly at the root of an import tree:
https://github.com/momentohq/client-sdk-go/blob/main/internal/protos/cachepubsub.proto#L3
> import "extensions.proto";

However your invocation is:
```
protoc -I=internal [...]
```

protoc looks for `extensions.proto` at `internal/extensions.proto` per the documentation, and it is not found because that's not where that file is in this repository. In fact, I'm not sure there is anything this invocation can use via that `-I` directive? Why isn't this using `-I=internal/protos`?

**Comment by pratik151192** [comment]
>  In fact, I'm not sure there is anything this invocation can use via that -I directive? Why isn't this using -I=internal/protos?

I experienced the same and did not see the error after changing the ```proto_path``` or ```-I``` directive to ```internal/protos``` .  However, ```--go_out``` and ```--go-grpc_out``` should also be ```internal/protos``` and not internal. The ```MakeFile``` suggests to use those options for ```protoc```, the same one which @pgautier404 has posted. I believe it should change to 

```
protoc -I=internal/protos --go_out=internal/protos --go_opt=paths=source_relative --go-grpc_out=internal/protos --go-grpc_opt=paths=source_relative internal/protos/*.proto
```

I am not sure how we were developing before though. The MakeFile also needs to be updated in that case.

**Comment by pratik151192** [comment]
So @pgautier404 and I verified the diff on the proto generated files and it is doing the right thing. The MakeFile was updated with the updated commands to ```internal/protos``` as a part of this PR https://github.com/momentohq/client-sdk-go/pull/332. This issue can be closed.
