### ISSUE TITLE
Fix all golint errors

### ISSUE THREAD

**Issue by eaddingtonwhite** [momentohq/client-sdk-go#45]
Currently getting 75 golint errors when I run.

```bash
$ golint incubating internal momento examples | wc -l
      75
```
We should fix these and add a lint step to Make file to make sure all are passing.

**Comment by schwern** [comment]
> NOTE: Golint is https://github.com/golang/go/issues/38968. There's no drop-in replacement for it, but tools such as [Staticcheck](https://staticcheck.io/) and go vet should be used instead.

Should we move to `go vet` first and then fix the errors?
